version: '3.8'

services:
  
  # Microservicio de Catálogo
  ms-pago:
    build:
      context: ..
    container_name: ms-pago
    ports:
      - "5003:5003"  # El contenedor expone el puerto 5001
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true