services:
  
  # Microservicio de Catálogo
  ms-pagos:
    image: mspagos:v1.0
    container_name: ms-pagos
    depends_on:
      - ecommerce_app
    ports:
      - 5003:5000
    networks:
      - ecommerce_network
    environment:
      - FLASK_CONTEXT=${FLASK_CONTEXT}
      - DEV_DB_URI=${DEV_DB_URI}

networks:
  ecommerce_network:
    external: true